### ISSUE TITLE
Menü-Probleme

### ISSUE THREAD

**Issue by Exidu** [LoreGamedia/ProjectRoughEastern#1]
## Sound-bug

Wenn man im menü unter den punkt System versucht in jedwiger variante versucht die Geräusche des spiels egal ob es BGM, BGS oder SFX Volume ist der sound ändert sich nicht. [http://puu.sh/gfpqi/4c32f3bd13.jpg](Screenshot) wie in diesem beigelegten Screenshot zu sehen

## Speichern

Es ist was in einer vorherigen Version möglich war nicht zu speichern ich weiß nicht ob das Beabsichtigt war oder nicht.

**Comment by lukiono** [comment]
confirmed, will be fixed

**Comment by lukiono** [comment]
Fixed on [v0.00.004](/LoreGamedia/ProjectRoughEastern/releases/tag/v0.0.004)
